### PR TITLE
feat: support history view

### PR DESCRIPTION
**Pull request by Yeuoly**

### CODE REVIEW

**Comment by lxfater** [comment]
Please provide some screenshots, as it would be easier to review.

**Comment by Yeuoly** [comment]
of course!
image

**Comment by lxfater** [comment]
Check if it conflicts with the undo feature, then I will merge it.

**Comment by Yeuoly** [comment]
I have already tested it. at least, it works in my testcases

**Comment by lxfater** [comment]
thanks

**Pull request merged**
